// toolbox-source/omni-tools/src/components/ToolLayout.tsx
import { Box } from '@mui/material';
import React, { ReactNode } from 'react';
import { Helmet } from 'react-helmet';
import ToolHeader from './ToolHeader';
import { useTranslation } from 'react-i18next';
import { ToolCategory } from '@tools/defineTool';
import { FullI18nKey } from '../i18n';
import { getI18nNamespaceFromToolCategory } from '../utils/string';
import type { IconifyIcon } from '@iconify/react';

export default function ToolLayout({
  children,
  i18n,
  type
}: {
  icon?: IconifyIcon | string;
  type: ToolCategory;
  fullPath: string;
  children: ReactNode;
  i18n: {
    name: FullI18nKey;
    description: FullI18nKey;
    shortDescription: FullI18nKey;
  };
}) {
  const { t } = useTranslation([
    'translation',
    getI18nNamespaceFromToolCategory(type)
  ]);
  const toolTitle = t(i18n.name);
  const toolDescription = t(i18n.description);

  return (
    <Box minHeight="100vh" sx={{ backgroundColor: 'background.default' }}>
      <Helmet>
        <title>{`${toolTitle} - 工具盒子`}</title>
      </Helmet>
      <Box
        component="header"
        position="sticky"
        top={0}
        zIndex={20}
        height="40px"
        display="flex"
        alignItems="center"
        gap={1}
        px={2}
        sx={{
          borderBottom: '1px solid',
          borderColor: 'divider',
          backgroundColor: 'rgba(255,255,255,.96)',
          backdropFilter: 'blur(8px)',
          fontSize: 12
        }}
      >
        <a href="/toolbox" style={{ color: '#315f9b', fontWeight: 700, textDecoration: 'none' }}>
          工具盒子
        </a>
        <span aria-hidden="true" style={{ color: '#8a94a4' }}>/</span>
        <strong style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {toolTitle}
        </strong>
      </Box>
      <Box width={{ xs: 'calc(100% - 28px)', md: '85%' }} maxWidth="1280px" mx="auto" pb={7}>
        <ToolHeader title={toolTitle} description={toolDescription} />
        {children}
      </Box>
    </Box>
  );
}

// toolbox-source/it-tools/src/layouts/tool.layout.vue
<script lang="ts" setup>
import { useHead } from '@vueuse/head';
import type { HeadObject } from '@vueuse/head';
import { useRoute } from 'vue-router';

const route = useRoute();
const { t } = useI18n();
const i18nKey = computed<string>(() => route.path.replace(/^\//, ''));
const toolTitle = computed<string>(() => t(`tools.${i18nKey.value}.title`, String(route.meta.name ?? '')));
const toolDescription = computed<string>(() => t(
  `tools.${i18nKey.value}.description`,
  String(route.meta.description ?? ''),
));
const head = computed<HeadObject>(() => ({
  title: `${toolTitle.value} - 工具盒子`,
  meta: [{ name: 'description', content: toolDescription.value }],
}));
useHead(head);
</script>

<template>
  <div class="platform-tool-shell">
    <header class="platform-tool-bar">
      <a href="/toolbox">工具盒子</a>
      <span aria-hidden="true">/</span>
      <strong>{{ toolTitle }}</strong>
    </header>
    <main class="platform-tool-main">
      <div class="platform-tool-heading">
        <h1>{{ toolTitle }}</h1>
        <p>{{ toolDescription }}</p>
      </div>
      <div class="platform-tool-content">
        <slot />
      </div>
    </main>
  </div>
</template>

<style lang="less" scoped>
.platform-tool-shell {
  min-height: 100vh;
  color: #172033;
  background: #f3f5f7;
}
.platform-tool-bar {
  position: sticky;
  z-index: 20;
  top: 0;
  display: flex;
  height: 40px;
  align-items: center;
  gap: 9px;
  padding: 0 16px;
  border-bottom: 1px solid #dce2ea;
  color: #687386;
  font-size: 12px;
  background: rgb(255 255 255 / 96%);
  backdrop-filter: blur(8px);
}
.platform-tool-bar a {
  color: #315f9b;
  font-weight: 700;
  text-decoration: none;
}
.platform-tool-bar strong {
  overflow: hidden;
  color: #172033;
  font-weight: 600;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.platform-tool-main {
  box-sizing: border-box;
  max-width: 1280px;
  margin: 0 auto;
  padding: 28px 24px 56px;
}
.platform-tool-heading {
  max-width: 760px;
  margin: 0 auto 24px;
}
.platform-tool-heading h1 {
  margin: 0;
  font-size: 28px;
  font-weight: 650;
  letter-spacing: -0.025em;
}
.platform-tool-heading p {
  margin: 8px 0 0;
  color: #687386;
  font-size: 13px;
  line-height: 1.6;
}
.platform-tool-content {
  display: flex;
  flex-flow: row wrap;
  justify-content: center;
  gap: 16px;
}
.platform-tool-content :deep(> *) {
  flex: 0 1 600px;
}
@media (max-width: 640px) {
  .platform-tool-main { padding: 22px 14px 40px; }
}
</style>
